### ISSUE TITLE
NEI Support 4.4.3a

### ISSUE THREAD

**Issue by xKillerbees** [lorddusk/HQM#115]
I'm unable to look up recipes of items within quests.

HQM Version: 4.4.3a
Forge Version: forge-1.7.10-10.13.4.1566-1.7.10-universal.jar
ForgeModLoader log: attached
Detailed description of the bug and pictures if applicable: Open up quest, hit 'R' to search recipe, nothing happens. 4.4.2 does not have this issue.

[fml-client-latest.txt](https://github.com/lorddusk/HQM/files/53104/fml-client-latest.txt)

**Comment by way2muchnoise** [comment]
Since we added hotkeys for editing R is the key to short cut for the rename EditMode. Either change that one or change the one for NEI.

Although I added a escape for non edit mode. It now doesn't check for hotkeys (only backspace will work).

**Comment by xKillerbees** [comment]
http://pastebin.com/VKEnmcug

Tried compiling the source and it worked great on client. On server it crashed with this error.

Forge 1558
HQM 4.4.3a(newest compiled)

**Comment by way2muchnoise** [comment]
Wut we fixed that crash like a week ago how van it still be a thing @lorddusk ?

**Comment by lorddusk** [comment]
No clue.

**Comment by lorddusk** [comment]
Found the issue. @way2muchnoise in your copy of the code the CommonProxy is still wrong. It still thinks the Server is a Client. (I fixed that on my end)

https://github.com/way2muchnoise/HQM/blob/b0cfe0c123ae69cb2805038d9cb10972957e407a/src/main/java/hardcorequesting/proxies/CommonProxy.java

**Comment by way2muchnoise** [comment]
@lorddusk I guess you never pushed that then. Since my fork is even with the master

**Comment by lorddusk** [comment]
yeah, I just did.
